name: Build Driver Module for MuMu

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential git cmake
        sudo apt-get install -y gcc-x86-64-linux-gnu
        sudo apt-get install -y linux-headers-$(uname -r)
        sudo apt-get install -y libelf-dev elfutils
        sudo apt-get install -y flex bison
        sudo apt-get install -y linux-headers-generic
    
    - name: Download Android NDK
      run: |
        wget https://dl.google.com/android/repository/android-ndk-r25c-linux.zip
        unzip android-ndk-r25c-linux.zip
        echo "ANDROID_NDK_HOME=$PWD/android-ndk-r25c" >> $GITHUB_ENV
        
    - name: Build Driver Module
      run: |
        cd rwProcMem33Module/rwProcMem_module
        make ARCH=x86_64 CROSS_COMPILE=x86_64-linux-gnu- -C /usr/src/linux-headers-$(uname -r) M=$PWD
        
    - name: Build Test Program
      run: |
        cd rwProcMem33Module/testCEServer
        $ANDROID_NDK_HOME/ndk-build APP_ABI=x86_64
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: driver-files-mumu
        path: |
          rwProcMem33Module/rwProcMem_module/*.ko
          rwProcMem33Module/testCEServer/libs/x86_64/*
